run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - goconst
    - gocyclo
    - godot
    - misspell
    - revive
    - whitespace
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: avito_internship_PR
  gosec:
    excludes:
      - G101
      - G104
  revive:
    rules:
      - name: exported
        arguments:
          - checkPrivateReceivers
      - name: package-comments
      - name: var-naming
      - name: receiver-naming
      - name: indent-error-flow
      - name: error-return
      - name: error-strings
      - name: receiver-naming
      - name: increment-decrement
      - name: error-naming

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
    - path: internal/.*/infrastructure/.*
      text: "exported.*should have comment"
    - linters:
        - gosec
      text: "G104"

output:
  formats: colored-line-number

service:
  golangci-lint-version: 1.54.2